name: Django Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install psycopg2-binary
        run: |
          pip install psycopg2-binary
          

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8

      

      - name: Django Testing
        run: |
          python3 manage.py test